CREATE TABLE IF NOT EXISTS WORKFLOW
(
  ID_ BIGINT PRIMARY KEY,
  KEY_ BIGINT,
  BPMN_PROCESS_ID_ VARCHAR,
  VERSION_ INT,
  RESOURCE_ VARCHAR,
  TIMESTAMP_ BIGINT
);

CREATE TABLE IF NOT EXISTS WORKFLOW_INSTANCE
(
	ID_ BIGINT PRIMARY KEY,
	PARTITION_ID_ INT,
	KEY_ BIGINT,
	INTENT_ VARCHAR,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ACTIVITY_ID_ VARCHAR,
	SCOPE_INSTANCE_KEY_ BIGINT,
	PAYLOAD_ VARCHAR,
	WORKFLOW_KEY_ BIGINT,
  TIMESTAMP_ BIGINT
);

CREATE TABLE IF NOT EXISTS INCIDENT
(
	ID_ BIGINT PRIMARY KEY,
	KEY_ BIGINT,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ACTIVITY_INSTANCE_KEY_ BIGINT,
	JOB_KEY BIGINT,
	ERROR_TYPE_ VARCHAR,
	ERROR_MSG_ VARCHAR
);
